DjangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views


urlpatterns = [
    # url(r'^$', views.homepage, name="home"),
    path('myapp/', include('myapp.urls')),
    path('django08/', include('django08.django08_url')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

]

# handler404 = views.page_not_found
# handler500 = views.server_error

myapp/urls.py
from django.urls import path
from myapp import views, admin_views
from django.conf.urls import include
from myapp.view.BaseView import BaseView
from myapp.views import Jsontable102List


app_name = 'myapp'


user_patterns = [
    path('', views.userhomepage, name="userhomepage"),

]

admin_patterns = [
    path('', admin_views.adminhomepage, name="adminhomepage"),
    path('show_chart_table', admin_views.show_chart_table, name="show_chart_table"),
    path('blake_show13', views.blake_show13),

]

urlpatterns = [
    path('', views.homepage, name="home"),
    path('handlenmea/', views.handlenmea, name="handlenmea"),
    path('handlejson/', views.handlejson, name="handlejson"),

    path('test', views.test, name='test'),
    path('blake_test', views.blake_test, name='blake_test'),
    path('show13', views.Show13),
    path('blake_show13', views.blake_show13),
    path('testjs102/',Jsontable102List.as_view(),name='testjs102'),

    path('login/', views.login, name="login"),
    path('registerpage/', views.registerpage, name="registerpage"),
    path('register/', views.register, name="register"),
    path('line_basic/', views.line_basic, name="line_basic"),
    path('datatable_basic/', views.datatable_basic, name="datatable_basic"),
    path('line_basic_xAxis/', views.line_basic_xAxis, name="line_basic_xAxis"),
    path('user/', include(user_patterns)),
    path('admin/', include(admin_patterns)),


]

templates/index.html
<!-- index.html -->
<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<title>首页</title>
<script src="/static/jquery-2.2.2.min.js"></script>
</head>
<body>
	<h1>这是测试网页</h1>
	<hr>
	{{hello}}
	<hr>
	这是相当华丽的分割线
	<br/>
	<br/>
	<hr>
	<a href='/filepath/'>文件地址</a><br/>
	<a href='/index/'>index</a><br/>
	<a href='/selectPeopleCard/'>查找PeopleCard数据</a><br/>
	<a href='/selectMainTable/'>查找MainTable数据</a><br/>
	<br/>
	<br/>
	<form enctype="multipart/form-data" action="/uploadFile/" method="post">
		
		<input type="file" name="myfile" />
		<br/>
		<input type="submit" value="upload" /><br/>
	</form>
	<br/>
	<br/>
	<br/>
	<form enctype="multipart/form-data" action="/uploadFile1/" method="post">
		
		<input type="file" name="myfile" />
		<br/>
		<input type="submit" value="upload" />
		<a href="http://www.baidu.com/"><input type="button" value='百度'></a>

		<br/>
	</form>
<label for="username" class="sr-only">Username</label>
	<br/>
	<br/>
	<br/>
	

	
	<form enctype="multipart/form-data" action="/selectMainTable/" method="get">
		
		<label for='device_id'>unit_id:</label>
		<input id='device_id' type='text' name='device_id'><br/>
		<label for='travel_date'>驾驶日期:</label>
		<input type="date" id='user_date' name="user_date"/>
		<input type="submit" value="OK" /><br/>
	</form>
	<br/>
	<br/>
	
	
		<div class="a">
			baidu一下
		</div>
		<button>get请求数据</button>
		
</body>
</html>

<script>
	$('button').click(function(){
			$.get('index',function(data){
				$('div').append(data.unitid)
			})
	
	})

</script>

templates/indeximg.html
{% load static %}
<div style='margin:0 0 0 3%;border:1px solid grey;'>
	<img src="{% static 'images/zhuye.gif' %}" style='width:98%;'></img>
</div>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
	<!--{% load static %}-->
    <link rel="stylesheet" href="/static/bootstrap.min.css" style = "text/css">
    <!--<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" style = "text/css">-->
	<!--<link rel="stylesheet" href="{% static 'style.css' %}" style = "text/css">-->
	<link rel="stylesheet" href="/static/style.css" style = "text/css">
    <script type="text/javascript">
	 function checkform(){

	 if(document.login.username.value==""/* ||document.login.password.value=="" */){
	 alert("请输入用户名！");
	 return false;
	 }

	 if(/* document.login.username.value==""|| */document.login.password.value==""){
	 alert("请输入密码！");
	 return false;
	 }


	  /* if(document.studentUpda.upassword1.value!=document.studentUpda.upassword2.value){
	 alert("密码不统一！");
	 return false;
	 } */
	 }

	 </script>
</head>
<body>
    <div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="menu">
					</ul>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<!-- Start Sign In Form -->
					<form action="{% url 'myapp:login' %}" class="fh5co-form animate-box" data-animate-effect="fadeIn" method="post" name="login" onsubmit="return checkform();">
						<center><h2>登录</h2></center>
						<div class="form-group">
							<label for="username" class="sr-only">Username</label>
							<input type="text" class="form-control" id="username"  name="username" placeholder="username" autocomplete="off">
						</div>
						<div class="form-group">
							<label for="password" class="sr-only">Password</label>
							<input type="password" class="form-control" id="password" name="password" placeholder="password" autocomplete="off">
						</div>
						<center>
							<div style="color:red">
								{% if LoginResult == "1" %}
									用户名错误
								{% endif %}
								{% if LoginResult == "2" %}
									密码错误
								{% endif %}
								{% if LoginResult == "3" %}
									你已被禁用系统，请联系管理员解除禁用!
								{% endif %}

								{{error}}

							</div>
                    	</center>

						<div class="form-group">
						<center>
							<a href="{% url 'myapp:registerpage' %}"><input type="button" value='注册' class="btn btn-primary"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<input type="reset" value="重填" class="btn btn-primary">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<input type="submit" value="登录" class="btn btn-primary">

						</center>
						</div>
					</form>
					<!-- END Sign In Form -->

				</div>
			</div>
			<div class="row" style="padding-top: 60px; clear: both;">
				<div class="col-md-12 text-center">
                    <a href="#">联系我们</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">开放平台</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">认证空间</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">官方微博</a>&nbsp;&nbsp;&nbsp;
                    <a href="#" target="_blank">在线客服</a>
                </div>
			</div>

			<div class="row" style="padding-top: 60px; clear: both;">
				<div class="col-md-12 text-center">

				Copyright &copy; 2017 - 2018 WangHongLiang. All Rights Reserved.<br />
                王洪亮&nbsp;&nbsp;&nbsp;版权所有





				</div>
			</div>

		</div>



</body>
</html>

templates/myindex.html
<html>
<head>
    <meta charset="UTF-8">
    <title>功能页面</title>
    {% load static %}
    <link REL="SHORTCUT ICON" HREF="{% static 'images/favicon.ico' %}"/>
    </head>
<body>
<div id="app">
    <v-app>
        <div style="width:100%;height:70px;background:#26A69A;">

        </div>
        {% block content%}
        {% endblock %}
    </v-app>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css" >
	<link rel="stylesheet" href="/static/style.css" >
    <script type="text/javascript">
	 function checkform(){

	 if(document.register.username.value==""/* ||document.login.password.value=="" */){
	 alert("请输入用户名！");
	 return false;
	 }

	 if(/* document.login.username.value==""|| */document.register.password.value==""){
	 alert("请输入密码！");
	 return false;
	 }


	 if(document.register.password.value!=document.register.password1.value){
	 alert("密码不统一！");
	 return false;
	 }
	 }

	 </script>
</head>
<body>
    <div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="menu">
					</ul>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<!-- Start Sign In Form -->
					<form action="{% url 'myapp:register' %}" class="fh5co-form animate-box" data-animate-effect="fadeIn" method="post" name="register" onsubmit="return checkform();">
						<center><h2>注册</h2></center>
						<div class="form-group">
							<!--<label for="username" class="sr-only">Username</label>-->
							<input type="text" class="form-control" id="username"  name="username" placeholder="username" autocomplete="off">
						</div>
						<div class="form-group">
							<!--<label for="password" class="sr-only">Password</label>-->
							<input type="password" class="form-control" id="password" name="password" placeholder="password" autocomplete="off">
						</div>
                        <div class="form-group">
							<!--<label for="password" class="sr-only">Password</label>-->
							<input type="password" class="form-control" id="password1" name="password1" placeholder="input password again" autocomplete="off">
						</div>
                        <center>
							<div style="color:red">
								{{error}}
							</div>
                    	</center>

						<div class="form-group">
						<center>
							<input type="submit" value="注册" class="btn btn-primary">

						</center>
						</div>
					</form>
					<!-- END Sign In Form -->

				</div>
			</div>
			<div class="row" style="padding-top: 60px; clear: both;">
				<div class="col-md-12 text-center">
                    <a href="#">联系我们</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">开放平台</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">认证空间</a>&nbsp;&nbsp;&nbsp;
                    <a href="#">官方微博</a>&nbsp;&nbsp;&nbsp;
                    <a href="#" target="_blank">在线客服</a>
                </div>
			</div>

			<div class="row" style="padding-top: 60px; clear: both;">
				<div class="col-md-12 text-center">

				Copyright &copy; 2017 - 2018 WangHongLiang. All Rights Reserved.<br />
                王洪亮&nbsp;&nbsp;&nbsp;版权所有





				</div>
			</div>

		</div>



</body>
</html>

templates/test.html
{% extends 'myindex.html'%}
{% block content%}

{% load static %}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/test.css'%}">
<script type="text/javascript" charset="utf8" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
<script src="https://code.highcharts.com.cn/highstock/highstock.js" type="text/javascript"></script>

    <div id="loading">
         <img src="/static/images/loading.gif" alt="loading..." style="width:80%;height:80%;"/>
    </div>
    <div>
        <span id="pagetitle">highcharts & datatable测试页面</span>
    </div>

    <div id="contain"></div>
	<div id="two">
        <p id="title" style="margin:0 38%;">车辆</p>
        <button id="show">筛选所需列</button>
    </div>

    <div id="cbox" style="display:none;">
        {% for i in tablehead%}
        <label class="typecheck"><input type="checkbox" value="{{i.title}}" class="cb" checked>{{i.title}}</label>
        {% endfor %}
        <input type="button" id="select_all" value="全选" >
        <input type="button" id="cancle_all" value="全不选">
    </div>

    <div id="huabiaoge">
        <table id="example" class="cell-border compact">
        </table>
    </div>
    <script>
         var data1 = {{context|safe}};
         var pt = {{pt|safe}};
         var gsq = {{gsq|safe}};
		 var lat = {{lat|safe}};
         var vel = {{vel|safe}};
         
         var tablehead = {{tablehead|safe}};
    </script>
    <script src="{% static 'js/test.js' %}"></script>
{% endblock %}

templates/testTrip.html
{% extends 'myindex.html'%}

{% block content%}

    <h3>试试看基于类的视图Jsontable102-ListView 用来获取某个 model 中的所有数据</h3>
    <ul>
        {% for js102 in allJs102 %}
            <li>{{ js102.metadata_positioning_data_positioning_time }}</li>
        {% endfor %}
    </ul>

{% endblock%}

templates/updatejson.html
<div>
<p style="margin:3% 2%;">上传原始Json数据</p>
  <form  action="{% url 'myapp:handlejson' %}" method="post" enctype="multipart/form-data" style="margin:10% 5%;">
  <input type="file" name="json" >
  <input style='background:#26A69A;border-radius:2px;color:white;padding:4px;' type="submit" value="选好Json文件点此上传">
 </form>
</div>

templates/updatenmea.html
<div>
  <p style="margin:2% 2%;">上传NMEA文件</p>
  <form action="{% url 'myapp:handlenmea' %}" method="post" enctype="multipart/form-data" style="margin:10% 5%;">
  <input type="file" name="nmea" >
  <input style='background:#26A69A;border-radius:2px;color:white;padding:4px;' type="submit" value="选好Nmea文件点此上传">
 </form>
</div>