DjangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views


urlpatterns = [
    # url(r'^$', views.homepage, name="home"),
    path('myapp/', include('myapp.urls')),
    path('django08/', include('django08.django08_url')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

]

# handler404 = views.page_not_found
# handler500 = views.server_error

myapp/urls.py
from django.urls import path
from myapp import views, admin_views
from django.conf.urls import include
from myapp.view.BaseView import BaseView
from myapp.views import Jsontable102List


app_name = 'myapp'


user_patterns = [
    path('', views.userhomepage, name="userhomepage"),

]

admin_patterns = [
    path('', admin_views.adminhomepage, name="adminhomepage"),
    path('show_chart_table', admin_views.show_chart_table, name="show_chart_table"),
    path('blake_show13', views.blake_show13),

]

urlpatterns = [
    path('', views.homepage, name="home"),
    path('handlenmea/', views.handlenmea, name="handlenmea"),
    path('handlejson/', views.handlejson, name="handlejson"),

    path('test', views.test, name='test'),
    path('blake_test', views.blake_test, name='blake_test'),
    path('show13', views.Show13),
    path('blake_show13', views.blake_show13),
    path('testjs102/',Jsontable102List.as_view(),name='testjs102'),

    path('login/', views.login, name="login"),
    path('registerpage/', views.registerpage, name="registerpage"),
    path('register/', views.register, name="register"),
    path('line_basic/', views.line_basic, name="line_basic"),
    path('datatable_basic/', views.datatable_basic, name="datatable_basic"),
    path('line_basic_xAxis/', views.line_basic_xAxis, name="line_basic_xAxis"),
    path('user/', include(user_patterns)),
    path('admin/', include(admin_patterns)),


]

templates/user/blake_test.html
{% extends 'myindex.html'%}
{% block content%}

{% load static %}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/test.css'%}">
<script type="text/javascript" charset="utf8" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
<script src="https://code.highcharts.com.cn/highstock/highstock.js" type="text/javascript"></script>

    <div id="loading">
         <img src="/static/images/loading.gif" alt="loading..." style="width:80%;height:80%;"/>
    </div>
    <div>
        <span id="pagetitle">highcharts & datatable测试页面</span>
    </div>

    <div id="contain"></div>
	<div id="two">
        <p id="title" style="margin:0 38%;">车辆</p>
        <button id="show">筛选所需列</button>
    </div>

    <div id="cbox" style="display:none;">
        {% for i in tablehead%}
        <label class="typecheck"><input type="checkbox" value="{{i.title}}" class="cb" checked>{{i.title}}</label>
        {% endfor %}
        <input type="button" id="select_all" value="全选" >
        <input type="button" id="cancle_all" value="全不选">
    </div>

    <div id="huabiaoge">
        <table id="example" class="cell-border compact">
        </table>
    </div>
    <script>
         var data1 = {{context|safe}};
         var pt = {{pt|safe}};
         var gsq = {{gsq|safe}};
		 var lat = {{lat|safe}};
         var vel = {{vel|safe}};
         var satellite_num = {{satellite_num|safe}};
         
         var tablehead = {{tablehead|safe}};
    </script>
    <script src="{% static 'js/blake_test.js' %}"></script>
{% endblock %}

templates/user/index.html
<html>
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    {% load static %}
    <link REL="SHORTCUT ICON" HREF="{% static 'images/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div id="app">
    <v-app>
        <v-container><span class='float-right blue--text'>总要有点东西admin页面的账密均为admin</span></v-container>
        <v-card>
            <v-toolbar flat color="#26A69A" dark>
              <v-toolbar-title>工具列表</v-toolbar-title>
            </v-toolbar>
            <v-tabs vertical>
              <v-tab class="title">
                <v-icon left>mdi-account</v-icon>
                主页内容
              </v-tab>
              <v-tab class="title">
                <v-icon left>mdi-arrow-up-bold-box-outline</v-icon>
                上传Nmea
              </v-tab>

              <v-tab class="title">
                <v-icon left>mdi-arrow-up-bold-box</v-icon>
                上传json
              </v-tab>

			  <v-tab class="title">
                <v-icon left>mdi-dialpad</v-icon>
                折线表格
              </v-tab>

              <v-tab class="title">
                <v-icon left>mdi-car</v-icon>
                study_test
              </v-tab>

              <v-tab class="title">
                <v-icon left>mdi-run</v-icon>
                测试页面
              </v-tab>

			  <v-tab class="title">
                <v-icon left>mdi-book</v-icon>
                后台页面
              </v-tab>


              <v-tab-item>
                {% include 'indeximg.html'%}
              </v-tab-item>

              <v-tab-item>
                {% include 'updatenmea.html'%}
              </v-tab-item>


              <v-tab-item>
                {% include 'updatejson.html'%}
              </v-tab-item>

			  <v-tab-item>
                <h3 style="margin:10% 15%;"><a href = "{% url 'myapp:test' %}">查看一个highcharts/datatable的例子页面</a></h3>
              </v-tab-item>

			  <v-tab-item>
                <h3 style="margin:10% 15%;"><a href = "{% url 'myapp:blake_test' %}">blake_study highcharts/datatable</a></h3>
              </v-tab-item>

			  <v-tab-item>
                <h3 style="margin:10% 15%;"><a href="{% url 'myapp:testjs102' %}">试试看基于类的视图Jsontable102</a></h3>
			  </v-tab-item>

			  <v-tab-item>
                {% include 'updatejson.html'%}
              </v-tab-item>

            </v-tabs>
          </v-card>
    </v-app>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
  <script src="{% static 'js/indexjs.js' %}"></script>
</body>
</html>

templates/user/userhomepage.html
<!DOCTYPE html>
<html lang="en">
<head>
<base href="<%=basePath%>">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" href="/static/css/pintuer.css">
    <link rel="stylesheet" href="/static/css/admin.css">
    <script src="/static/js/jquery.js"></script>
</head>
<body style="background-color:#02203C;">
<div class="header bg-main">
  <div class="logo margin-big-left fadein-top">
    <h1><img src="/static/images/7.jpg" class="radius-circle rotate-hover" height="50" alt="" />电厂节能数据研究与分析</h1>
  </div>
  <div class="head-r"> &nbsp;<a class="button button-little bg-red" href="login/login.jsp">退出登录</a> </div>
</div>
<div class="leftnav">
  <div class="leftnav-title"><strong><span class="icon-list"></span>菜单列表</strong></div>
  <h2><span class="icon-user"></span>用户中心</h2>
  <ul style="display:block">
<li><a href="project/NewsAdd.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>添加公告</font></a></li>
<li><a href="news/list" target="right"><font color="#fff"><span class="icon-caret-right"></span>公告管理</font></a></li>

 <li><a href="project/AddLogin.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>添加用户</font></a></li>
    <li><a href="users/list" target="right"><font color="#fff"><span class="icon-caret-right"></span>删除用户</font></a></li>

   <li><a href="users/list1" target="right"><font color="#fff"><span class="icon-caret-right"></span>冻结用户/解冻用户</font></a></li>

    <li><a href="project/ChangePassword.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>修改密码</font></a></li>

     <li><a href="dcstodb/list" target="right"><font color="#fff"><span class="icon-caret-right"></span>数据库设计规范</font></a></li>
    <li><a href="MulAnalysis/list" target="right"><font color="#fff"><span class="icon-caret-right"></span>记录的数据</font></a></li>
  </ul>
  <h2><span class="icon-pencil-square-o"></span>煤耗+主汽温度（机侧）分析</h2>
  <ul>

  <li><a href="Bnsttresult/listAccept" target="right"><font color="#fff"><span class="icon-caret-right"></span>合格数据</font></a></li>
  <li><a href="Bnsttresult/listReject" target="right"><font color="#fff"><span class="icon-caret-right"></span>不合格数据</font></a></li>
  <li><a href="Bnsttresult/listDelay" target="right"><font color="#fff"><span class="icon-caret-right"></span>无法判断数据</font></a></li>

    <li><a href="project/Bnsttresultcount.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>结果汇总</font></a></li>
 <li><a href="Bnsttresult/listAllDown" target="right"><font color="#fff"><span class="icon-caret-right"></span>导出所有处理结果</font></a></li>
<!--     <li><a href="project/BnsttMap.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>结果查询</font></a></li> -->

  </ul>

   <h2><span class="icon-pencil-square-o"></span>煤耗+主汽温度（炉侧）分析</h2>
  <ul>
    <li><a href="Bnsbtggcsresult/listAccept" target="right"><font color="#fff"><span class="icon-caret-right"></span>合格数据</font></a></li>
  <li><a href="Bnsbtggcsresult/listReject" target="right"><font color="#fff"><span class="icon-caret-right"></span>不合格数据</font></a></li>
  <li><a href="Bnsbtggcsresult/listDelay" target="right"><font color="#fff"><span class="icon-caret-right"></span>无法判断数据</font></a></li>

    <li><a href="project/Bnsbtggcsresultcount.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>结果汇总</font></a></li>
    <li><a href="Bnsbtggcsresult/listAllDown" target="right"><font color="#fff"><span class="icon-caret-right"></span>导出所有处理结果</font></a></li>
    <!-- <li><a href="project/Bnsbtggcs.jsp" target="right"><font color="#fff"><span class="icon-caret-right"></span>结果查询</font></a></li>    -->
  </ul>

</div>

<script type="text/javascript">
$(function(){
  $(".leftnav h2").click(function(){
	  $(this).next().slideToggle(200);
	  $(this).toggleClass("on");
  })
  $(".leftnav ul li a").click(function(){
	    $("#a_leader_txt").text($(this).text());
  		$(".leftnav ul li a").removeClass("on");
		$(this).addClass("on");
  })
});
</script>



<ul class="bread">
  <li><a href="news/list1" target="right" class="icon-home" ><font color="#fff"> 首页</font></a></li>

 </ul>
<div class="admin">
 <iframe scrolling="auto"  src="news/list1" name="right" width="100%" height="100%"></iframe>
</div>
<div style="text-align:center;">
</div>
</body>
</html>